name: insergemobileapplication
description: Aplicativo movil para la empresa Inserge

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  camera: ^0.10.0+3
  carousel_slider: ^4.1.1
  clipboard: ^0.1.3
  cloud_firestore: null
  cupertino_icons: ^1.0.2
  firebase_auth: null
  firebase_core: null
  firebase_storage: null
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  flutter_unity_widget: ^2022.2.0
  http: ^0.13.5
  image_picker: ^0.8.6
  photo_view: ^0.14.0
  image_cropper: ^3.0.1
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logoinsergeX.png"

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
